### PR TITLE
Added templated files from previous meetings.

### PR DESCRIPTION
**Pull request by shaun-edwards**
Do not merge...

@gavanderhoorn, here is the templates for the meetings.  I'll update this PR when maintainers report back status.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Ok. Thanks. I'll take a look.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, I updated the status notes (still not complete, got a couple more responses this morning).

**Comment by gavanderhoorn** [comment]
Yeah, I saw that. Am currently updating / integrating slides.

**Comment by gavanderhoorn** [comment]
Can't send emails btw, authentication server is down.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, do you have the updated slides yet?  Can you also update the meeting notes.  I'll update some more status sections later this evening.  I'd like to send out the agenda for the next meeting tomorrow (Tuesday) along with the meeting notes from the previous meeting (i.e. this PR).

**Comment by gavanderhoorn** [comment]
I'll get right on it.

**Comment by gavanderhoorn** [comment]
Btw, with updated slides, you just mean the slides I used last time right?

**Comment by shaun-edwards** [comment]
Whatever slides you presented in the meeting...I didn't see a commit beyond my initial version.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, ping?

**Comment by gavanderhoorn** [comment]
Got side-tracked. Slides are up, going to work out my notes now.

**Comment by shaun-edwards** [comment]
+1...merging.

**Pull request merged**
